### DISCUSSION TITLE
Sftpgo webdav and floccus setup/config

### DISCUSSION THREAD

**Discussion by martin-forum** [floccusaddon/floccus#1555] [Q&A]
Hello,

maybe someone can help - for syncing my bookmarks with floccus, I have installed sftpgo with webdav. 

Sftpgo is up and running. Details - in a docker container, with http, only intranet and my Debian browser can rw over webdav. 

But - how do I have to setup/ config floccus?
All my attempts to get access to sftpgo webdav failed.

Any suggestion?

**Comment by Neurology0443** [comment]
Hey I got it working, here's my basic docker compose file. Keep in mind that I used self-signed certificates/domaines and traefik as reverse proxy. Also you need to create a basic user (not admin) in sftpgo. After that you add your domain and user in floccus and everything should work.

```
services:
  sftpgo:
    image: drakkan/sftpgo:latest
    container_name: sftpgo
    volumes:
      - data:/srv/sftpgo/data
      - config:/var/lib/sftpgo
#    ports:
#      - 8080:8080
#      - 2022:2022
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - SFTPGO_WEBDAVD__BINDINGS__0__PORT=8090
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sftpgo.entrypoints=websecure"
      - "traefik.http.routers.sftpgo.rule=Host(`sftpgo.domain.com`)"
      - "traefik.http.routers.sftpgo.tls=true"
      - "traefik.http.routers.sftpgo.middlewares=default-headers@file"
      - "traefik.http.routers.sftpgo.service=sftpgo"
      - "traefik.http.services.sftpgo.loadbalancer.server.port=8080"

      #WebDav

      - "traefik.http.routers.webdav.entrypoints=websecure"
      - "traefik.http.routers.webdav.rule=Host(`webdav.domain.com`)"
      - "traefik.http.routers.webdav.tls=true"
#      - "traefik.http.routers.webdav.priority=2"
      - "traefik.http.routers.webdav.service=webdav"
      - "traefik.http.services.webdav.loadbalancer.server.port=8090"


networks:
  default:
    external: true
    name: traefik-net


volumes:
  data:
    driver: local
    name: sftpgo_data
  config:
    driver: local
    name: sftpgo_config
```

Maybe you could give more details, your docker compose file ?
