### ISSUE TITLE
Add Dark Theme

### ISSUE THREAD

**Issue by xf-** [floccusaddon/floccus#894]
### Is your feature request related to a problem? Please describe.
Current state only fits the light theme

### Describe the solution you'd like
Add a media query that uses preferred theme and adjust the colors. Easiest is to use `var(--your-color)` and just overwrite a few variables after the switch.

**Comment by xf-** [comment]
This resolves the "issue" for me.

```css
@media (prefers-color-scheme: dark) {
  html .v-application .light-blue.lighten-5 {
    background-color: #333 !important;
    border-color: #333 !important;
  }

  html footer,
  html .theme--light.v-application,
  html .theme--light.v-card,
  html .v-application .white,
  html .v-btn.v-btn--has-bg {
    background-color: #000 !important;
    color: #ffffffde !important;
  }

  html .v-btn.v-btn--has-bg {
    background-color: #444 !important;
  }

  html .v-btn.v-btn--icon,
  html .v-label,
  html .v-input input,
  html .v-input textarea,
  html .v-input,
  html .v-icon,
  html .v-messages {
    color: #ffffffde !important;
  }

  html .v-expansion-panels .v-expansion-panel {
    background-color: #222 !important;
    border-color: #222 !important;
    color: #ffffffde !important;
  }

  html .v-input__slot::before {
    border-color: #eee !important;
  }
}
```

Also, I added this to get rid of huge scrollbars in Firefox
```css
html {
  scroll-behavior: smooth;
  scrollbar-width: thin;
  scrollbar-color: #ffffffde  #333;
}
```
